# Generated by Django 4.0.5 on 2022-06-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='book',
            name='images',
            field=models.ImageField(upload_to='images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Til'),
        ),
        migrations.AlterField(
            model_name='book',
            name='shirft',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Yozuv'),
        ),
    ]
