# Generated by Django 4.0.5 on 2022-06-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapi', '0003_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='book', to='booksapi.category', verbose_name='Toifa'),
        ),
    ]
