# Generated by Django 4.0.5 on 2022-06-24 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksapi', '0004_alter_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dokon Nomi/Brendi')),
                ('url', models.URLField(verbose_name='URL Manzil')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=9, verbose_name="Narxi (So'mda)")),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='booksapi.book')),
            ],
        ),
    ]
