# Generated by Django 4.0.5 on 2022-06-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksapi', '0005_booksource'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('job', models.CharField(max_length=250, verbose_name='Kasbi/Ishi qisqacha')),
                ('retext', models.TextField(verbose_name='Matn')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='booksapi.book')),
            ],
        ),
    ]
